### PR TITLE
Fix path calculation for config/private_pub.yml in private_pub.ru

### PR DESCRIPTION
**Pull request by yourcelf**
Fix path calculation for ``config/private_pub.yml`` in ``private_pub.ru``.
Fixes the following error while attempting to run
``rackup private_pub.ru -s thin -E production``:

    /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/private_pub-875b3de1711b/lib/private_pub.rb:23:in `read': Not a directory @ rb_sysopen - /home/dev/git/loomio/private_pub.ru/private_pub.yml (Errno::ENOTDIR)
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/private_pub-875b3de1711b/lib/private_pub.rb:23:in `load_config'
            from /home/dev/git/loomio/private_pub.ru:9:in `block in <main>'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
            from /home/dev/git/loomio/private_pub.ru:in `new'
            from /home/dev/git/loomio/private_pub.ru:in `<main>'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
            from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
            from /home/dev/.rbenv/versions/2.2.0/bin/rackup:23:in `load'
            from /home/dev/.rbenv/versions/2.2.0/bin/rackup:23:in `<main>'

### CODE REVIEW

**Comment by robguthrie** [comment]
Thanks @yourcelf. The private pub stuff is a little confusing as the private pub server is separate to Loomio, but it is installed in both places.

So, It's not expected that people run private pub from Loomio.. but it might be ok to support it if it's not a big deal.

Check out https://github.com/loomio/loomio-faye-server

**Comment by gdpelican** [comment]
What's the verdict on this, @robguthrie? Keep it or leave it? :japanese_ogre:

**Comment by robguthrie** [comment]
Yea, I think we can accept this. Looks like it would be useful.

**Comment by gdpelican** [comment]
Thanks @yourcelf!

**Pull request merged**
