### PR TITLE
Flesh out remaining EventBus restructure

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
This includes the CommentService branch, but I want to get that merged in before this.

**Comment by gdpelican** [comment]
These tests are passing! It's a gosh darn Christmas miracle.

I'm pretty confident in the e2ez covering angular functionality (the notifications test in particular is sooo good, thanks @robguthrie!). I'm a little less confident in the cucumber covering all of the beta functionality.

I'm going to smoke this on user-test soon. I'd really love another set of eyes to smoke with, as this is a somewhat big architecture change.

**Comment by gdpelican** [comment]
Are we happy to merge this @robguthrie ? Maybe @HSalmon and I can sit and do a final smoke on it tomorrow?

**Comment by robguthrie** [comment]
yes!

**Pull request merged**
