### PR TITLE
Include updated at date for context panel

### PR DESCRIPTION
**Pull request by HSalmon**
Addresses: https://github.com/loomio/loomio/issues/3227

screen shot 2016-04-21 at 11 54 50 am
screen shot 2016-04-21 at 1 20 06 pm

### CODE REVIEW

**Comment by HSalmon** [comment]
Might need a smoke test. @mhjb - maybe when you've got a spare moment? No urgency

**Comment by gdpelican** [comment]
I'll grab this one.

**Comment by gdpelican** [comment]
So I don't think we'll be guaranteed to have the latest version, since it's serialized out with the event. A test might be

- Make a thread
- Change the context
- Make a page's worth (30) comments
- The thing will (I think) be broken

We could look at serializing out the most recent version with the discussion page, or firing off another web request for it? I dunno I'm not too inspired by this change, especially given that it adds more network overhead /complexity to the most-visited page in the app. Thoughts @robguthrie ?

**Comment by robguthrie** [comment]
Yea.. I think we need to discuss architecture for this one. A discussion will need to serialize out the last  version record by default if we do this. That's possibly a n+1 thing which I'm not sure we want to do right now.

**Comment by mhjb** [comment]
Sing out if any input from me would be useful.

**Comment by HSalmon** [comment]
Happy to leave this until we've had an architecture discusssion :)

**Comment by robguthrie** [comment]
Let's close this for now.

**Pull request closed without merging**
