### PR TITLE
Add remote db rake tasks

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
Whoops, don't merge me just yet, I don't quite work.

**Comment by robguthrie** [comment]
this feels like it should be a separate gem to me.

**Comment by gdpelican** [comment]
I guess, but I'm not going to write a gem for it, I'm just going to use these commands. :)

**Comment by robguthrie** [comment]
We should be writing a function to create a safe database for developers to use, rather than using the production db. 3 Devs have production and I don't think any more should, so I won't accept this. Hope you agree about that in principal. Maybe we should fast track the sanitise production function?

**Pull request closed without merging**
