### PR TITLE
Add detected locale for non-signed in users.

### PR DESCRIPTION
**Pull request by denjello**
This is a fix for not catching the locale of users that aren't signed in as discussed here: #1858

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm, cool. @s01us, how does this fix sit with you?

**Comment by robguthrie** [comment]
This is stuff I wrote. Basically the cacheable thing is no longer a requirement - we can take out best_cachable_locale all together, which means that you can take out best_available_locale too.. and just put the logic directly into best_locale

**Comment by denjello** [comment]
@robguthrie - yeah that's what i recommended two weeks ago.
```
  def best_locale
    selected_locale || detected_locale || default_locale
  end
```

**Comment by robguthrie** [comment]
Oh OK cool. Go ahead with that then.

**Comment by denjello** [comment]
@robguthrie - btw. its ready to pull.

**Comment by robguthrie** [comment]
Thanks @denjello

**Pull request merged**
