### PR TITLE
Use current proposal / check styling for poll

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
screen shot 2018-04-04 at 8 55 59 am
screen shot 2018-04-04 at 8 56 12 am

**Comment by robguthrie** [comment]
you're on 🔥 ! Such a nice improvement

**Comment by robguthrie** [comment]
In the poll image, what is the state of the grey backgrounded option?

**Comment by gdpelican** [comment]
That's on hover

**Pull request merged**
