### PR TITLE
Update FAQ & add to contact page

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
contact-us

**Comment by robguthrie** [comment]
Looking good. Can we please change 'get in touch to talk pricing' to just 'Contact us if you're interested'.

Also can we change the group size limit text? I'm not quite sure what to say.. Something like we have a limit of 5000 members but if your group outgrows this we'll be sure to get in contact with you. 

Do we need to think about the page in terms of non loomio.org versions? What should it do then? redirect to sign_in?

@rdbartlett any thoughts?

**Comment by gdpelican** [comment]
Best IMO is:

- render 'help/faq' and social media links if hosted_by_loomio?
- Move the contact email (contact@loomio.org) into an ENV variable, so
folks can specify where they'd like their contact mail sent.

**Comment by HSalmon** [comment]
@robguthrie, @rdbartlett, @gdpelican - should I proceed with the suggestion above made?

**Comment by robguthrie** [comment]
yea, i think that's good.

**Comment by rdbartlett** [comment]
**What size groups work well on Loomio?**

Loomio currently works well for groups up to about 1000 people.

**Comment by HSalmon** [comment]
@robguthrie, @gdpelican - does this need any further modifications?

**Comment by robguthrie** [comment]
nope. let's do it!

**Comment by gdpelican** [comment]
:+1: The best!

**Comment by rdbartlett** [comment]
Nice on Salmon :fish:

**Pull request merged**
