### PR TITLE
set default job priority to 10, prioritise mailers, invitations first

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by robguthrie** [comment]
Just noticed we have a lot of Jobs in the DJ queue. Geocoding visits etc.. We need to prioritise invitation emails above these.

**Comment by gdpelican** [comment]
I've noticed that the slack webhooks are going through a bit slowly too, wonder if that's contributing? What other things are in the DJ queue?

**Comment by robguthrie** [comment]
Seems like there has been a spike of jobs. I'd need to install a DJ web interface to get a good understanding.. metabase seems to be choking on DJ queries.

**Comment by gdpelican** [comment]
Anyway this looks good to me 🍏

**Pull request merged**
