### PR TITLE
remove piwik and ensure ahoy tracks all url changes as views

### PR DESCRIPTION
**Pull request by robguthrie**
Wonder if we should remove Google analytics too.. Ahoy is way more useful for most stuff

### CODE REVIEW

**Comment by gdpelican** [comment]
Would love to remove GA; I certainly don't use it anymore, and if you + @mhjb don't either, I reckon it can go.

**Comment by robguthrie** [comment]
I think we should/could keep it on the marketing page.

**Comment by mhjb** [comment]
I use GA all the time

**Comment by gdpelican** [comment]
Looks good to me. :green_apple: Merge away!

**Pull request merged**
