### PR TITLE
markdown help page. needs translation applied to the strings

### PR DESCRIPTION
**Pull request by robguthrie**
The beginnings of a simple markdown tutorial.

### CODE REVIEW

**Comment by robguthrie** [comment]
@s01us i thought I'd offer to meet you half way on writing a markdown page. If you do the translations we're done.

**Comment by s01us** [comment]
looks pretty accessible. 
i'll sort that over the weekend

**Comment by s01us** [comment]
looks like this : 


could do with some more formatting work (I also had trouble with haml). 
I think the important thing is that there are some strings which are translatable which is better than having nothing.  

Note I've started a **help.en.yml** which I think we're going to want in the future.
once this is merged I can can get the help file started to be translated on Transifex

**Comment by s01us** [comment]
this is ready @robguthrie 

the code being indented in the `pre` I think is a hard one to fix and is related to the layout indentation from that's being made by haml?

if we care about that (because currently users copying and pasting those examples will get bad markdown because of all the white space), we could : 

- tell haml not to indent as it compiles? 
- use some nasty JS on page : 
  - ```javascript
      $('pre')[0].textContent.replace(/^\s{4,}\n/gm, 'BLANK\n').replace(/^\s{4,}/gm, "").replace(/BLANK\n/gm, '\n')
    ```

**Comment by mixmix** [comment]
Can we talk about this please.
I'm ok with stuff being dropped but I'm a bit upset about the lack of
clarity

**Pull request merged**
