### PR TITLE
Resquashed commit of avatar thumbnail fix.

### PR DESCRIPTION
**Pull request by s01us**
a cherry-pick of this now messy pull request : https://github.com/loomio/loomio/pull/1903

### CODE REVIEW

**Comment by denjello** [comment]
sweet.

**Comment by robguthrie** [comment]
Thanks @denjello and @s01us

**Comment by robguthrie** [comment]
So I just tested out the profile image stuff.. It seems to still exhibit the problem you have highlighted  @denjello ... I'm not sure that this fixed anything.

**Comment by denjello** [comment]
strange - for my installation it works as advertised. I'll have a look at the pull request and compare it one more time...

**Pull request merged**
