### PR TITLE
Change new user email defaults

### PR DESCRIPTION
**Pull request by mhjb**
I'm confused. I made this change, but it isn't reflected when I look at Patrick's email settings:

image

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm, default will only take place for new users (it doesn't touch existing records) so you'll have to make sure patrick has been wiped and recreated before you see the changes. You could try visiting `/development/email_settings_as_logged_in_user` to ensure the default is picked up correctly.

Also, I don't think we can get away with editing `schema.rb` directly, so we'll want to write a migration:

```
rails g migration set_new_email_defaults # => makes a new migration
```
```
# db/migrate/{{big_fat_timestamp}}_set_new_email_defaults.rb
class SetNewEmailDefaults < ActiveRecord::Migration
  def self.change
    change_column :users, :email_on_participation, :boolean, default: false
  end
end
```

relevant docs: http://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration

**Comment by mhjb** [comment]
thanks very much James.

**Comment by mhjb** [comment]
Thanks again James. It's looking good now I think.

image

Would it make sense to put it on clone or test to check that emails do what they oughta?

**Comment by gdpelican** [comment]
Sure, I've pushed this to clone for testing.

**Comment by mhjb** [comment]
Thanks James. FYI, @HSalmon is picking this up now

**Comment by gdpelican** [comment]
@HSalmon since this is a well-tested part of the app, we'll need to update
the tests to reflect the new intended functionality.

**Comment by gdpelican** [comment]
Closing in favour of #3403

**Pull request closed without merging**
