### PR TITLE
Move Intercom widget to avoid covering FAB

### PR DESCRIPTION
**Pull request by mhjb**
Can this be tested on an installation that has Intercom?

### Before

image

### After (I hope)

image

### CODE REVIEW

**Comment by gdpelican** [comment]
Seems ok to me; any other objections?

**Comment by mhjb** [comment]
did you have a chance to test it?

**Comment by gdpelican** [comment]
Yep works fine for me.

Could be a less specific selector though, since ids are unique

```
#intercom-launcher {
  right: 85px;
}
```

**Comment by mhjb** [comment]
I thought I needed a more specific selector than Intercom's own css uses

**Comment by rdbartlett** [comment]
I don't understand why you'd not use an ID for this.

**Comment by mhjb** [comment]
@rdbartlett both my version and @gdpelican use an ID — what are you saying?

**Comment by rdbartlett** [comment]
I was confused. Ignore please :)

**Comment by gdpelican** [comment]
Ah right. Well in any case this works for me and I'm merging it.

**Pull request merged**
