### PR TITLE
Retina shield support

### PR DESCRIPTION
**Pull request by marceloboeira**

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey great!

Would you mind posting a screenshot of the change, @marceloboeira?

**Comment by marceloboeira** [comment]
Not at all. Wait a minute.

**Comment by marceloboeira** [comment]
On FHD and retina screens the badges get distorted because the PNG support on those services is old. The http://shields.io project solve this with a middleware SVG support. 
screen shot 2015-02-10 at 9 07 47 pm

**Comment by gdpelican** [comment]
Looks good to me, thanks, @marceloboeira!

**Comment by marceloboeira** [comment]
@gdpelican :smile:

**Pull request merged**
