### PR TITLE
More robust group page threads

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by robguthrie** [comment]
Interesting. @gdpelican while you're in there, could you please change the behaviour of the page so that it immediately displays what we have in the RecordStore, rahter than waiting for the fetch to complete each time? 

Could also include loading symbol, but right now if we did an offline loomio, this page would not work and the other ones would mostly.

**Comment by gdpelican** [comment]
I think it does that, but I'll make sure. Seems like the right thing to do.

**Comment by gdpelican** [comment]
This is ready for smoke test / CR.

**Comment by robguthrie** [comment]
CR'd: This is a really nice improvement @gdpelican. Thank you.

**Pull request merged**
