### PR TITLE
Add USD

### PR DESCRIPTION
**Pull request by mhjb**
Before
=====
image
image

image

After
===
image
image

image

### CODE REVIEW

**Comment by robguthrie** [comment]
@mhjb is this ready to go?

**Comment by mhjb** [comment]
Yes I think so. But @rdbartlett as product owner should have a glance over it.

**Comment by mhjb** [comment]
Oops — I squashed, according to the tech manual instructions — but now there are 20-odd commits instead of one

**Comment by robguthrie** [comment]
let's run through the squash page when we meet today and I'll try to make
it clearer

**Comment by mhjb** [comment]
bonza

**Comment by rdbartlett** [comment]
:+1:

**Pull request merged**
