### PR TITLE
fix vote button colours + make them pop on hover

### PR DESCRIPTION
**Pull request by rdbartlett**
Updates vote icons so they use the same colour as the pie chart.

Gives vote buttons a shadow + 1px lift so they grab your attention on hover:

image

### CODE REVIEW

**Comment by AaronThornton00** [comment]
@rdbartlett  I haven't seen how your pop looks, but I think the usual way to do this is to raise the button (increase the box shadow). You can use the box shadow mixin I put in. The real ninja way is to create a ripple effect, but Inbox simply raises the button (check there FAB on press) :)

**Comment by AaronThornton00** [comment]
Nice work on the buttons though man. That has been screening out for ever

**Comment by gdpelican** [comment]
I reckon it's starting to feel like a really good time to get an icon designer on this, no?

**Comment by rdbartlett** [comment]
The .btn class provides shadow on hover. I just added the 1px vertical
shift to make it really bombastic.

**Comment by AaronThornton00** [comment]
Nice

**Pull request merged**
