### PR TITLE
Add motion_closed and motion_closed_by_user to salient items

### PR DESCRIPTION
**Pull request by HSalmon**
Addresses https://github.com/loomio/loomio/issues/3109

Does this need tests around it @gdpelican? Also, I noticed while I was testing it locally that it seemed like some of my own activity was showing up as unread. Will try and investigate further.

### CODE REVIEW

**Comment by gdpelican** [comment]
Hrm, would need a smoke test. I'll put it on my list. Can you push up to clone tomorrow after smoke testing the unread bug?

**Comment by gdpelican** [comment]
We need to add some events to the `author_thread_item!` call in the event bus, as stated here:
https://github.com/loomio/loomio/issues/3143

**Comment by HSalmon** [comment]
@robguthrie, we've got email-related failures in here

**Comment by robguthrie** [comment]
Looks like the same failures we fixed yesterday. Can you merge that work into this one?

**Comment by HSalmon** [comment]
@robguthrie, @gdpelican, if someone would be up for reviewing this that would be great :)

**Comment by gdpelican** [comment]
These events aren't being broadcast through the MessageChannelService, so we'll need to add that as well so they live update

repro of unwanted behaviour:
- User A closes a proposal while User B is viewing the inbox
- User B does not see that unread activity until reloading

**Comment by gdpelican** [comment]
Cool, this is a pre-existing issue that we're going to handle separately :green_apple:

**Pull request merged**
