### PR TITLE
Expand latest proposal on thread page

### PR DESCRIPTION
**Pull request by gdpelican**
With active proposal:
screen shot 2015-10-21 at 1 09 40 am

With recent closed proposal:
screen shot 2015-10-21 at 1 09 57 am

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey I wonder if we should maybe put a time limit (2 weeks? A month?) on the latest closed proposal being open, since the primary objective is to expose the set outcome feature and at that point people will likely stop caring about something which happened forever ago.

**Comment by rdbartlett** [comment]
Yeah cool. Stick a one month timeout on it and we'll see how it feels?

**Comment by gdpelican** [comment]
This is good for a look @robguthrie; sorry about the mildly unrelated webhook fix in there.

**Comment by robguthrie** [comment]
Looks great. thanks for giving me time to see. Merge if you're happy

**Pull request merged**
