### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by ChristophT**
Added some german translations. Still a lot of open keys but it's a start.

### CODE REVIEW

**Comment by ChristophT** [comment]
Merged changes.

**Comment by robguthrie** [comment]
Hi @ChristophT thanks for the translations! Unfortunately we have a different process for adding translations. 

Are you in the [Loomio Translators Group](https://www.loomio.org/g/cpaM3Hsv/loomio-community-translation)? There is an intro to translation using Transifex (our translation tool) which explains how to translate the tool.

I'd be delighted to hear any feedback you have about the docs and the process - please let me know how I can help.

**Comment by robguthrie** [comment]
Hi @ChristophT thanks for the translations! Unfortunately we have a different process for adding translations. 

Are you in the [Loomio Translators Group](https://www.loomio.org/g/cpaM3Hsv/loomio-community-translation)? There is an intro to translation using Transifex (our translation tool) which explains how to translate the tool.

I'd be delighted to hear any feedback you have about the docs and the process - please let me know how I can help.

**Comment by ChristophT** [comment]
Hi @robguthrie!
Thanks for the info, I'll have a look into the group and the tool in the next days.
So this PR will be closed and the translations have to be transferred to Transifex?

**Comment by robguthrie** [comment]
Actually, I think I can push them in. Reading up on it now..

**Comment by robguthrie** [comment]
Ok, I've manually uploaded the client.de.yml from the PR to Transifex. So that's great. Thanks for you work. Future translations are best done within Transifex unless you find it to be a bad experience - then we can talk about alternatives.

**Comment by ChristophT** [comment]
Glad it worked out! I will try Transifex next time.

**Comment by robguthrie** [comment]
Thanks again!

**Pull request closed without merging**
