### PR TITLE
Add reference to replied-to-comment in comment replies

### PR DESCRIPTION
**Pull request by HSalmon**
Thought this might be a good interim thing to implement while we consider more complicated options.

screen shot 2016-05-02 at 2 56 43 pm

[Trello card](https://trello.com/c/7whXZS1b/1326-add-reference-to-replied-to-comment-in-comment-replies)
[Loomio discussion](https://www.loomio.org/d/lCfoxy9v/ux-replies-to-comments)

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm, this will run into a problem when you're replying to something out of the current event window.

screen shot 2016-05-03 at 11 25 19 am
(note how the link is undefined because comment.parent() isn't loaded)

We'll have to deal with this case somehow, as I don't think it'll be all that uncommon.

**Comment by robguthrie** [comment]
I seem to remember it was an AMS bug keeping us from serializing the parent
by default. Can we revisit if serializing the parent comment is possible
now?

**Comment by HSalmon** [comment]
I can take a look at that @robguthrie

**Comment by gdpelican** [comment]
Even given that the parent comment is loaded, we get into weirdness with
trying to load and manage multiple windows of events here. I think we need
to ensure the page is reloaded here if the target comment is outside the
window.

**Comment by robguthrie** [comment]
Yea.. I just don't think the effort is worth it right now. I think to do
this properly we need to be able to dynamically load a new window of
items.. and that is a bit bigger than the current scope. I'd rather not
spin cycles on this.

**Comment by gdpelican** [comment]
Gonna close, and we'll revisit laters.

**Pull request closed without merging**
