### PR TITLE
Add contact us option to user dropdown

### PR DESCRIPTION
**Pull request by gdpelican**
This:
screen shot 2015-10-05 at 5 45 31 am

And this:
screen shot 2015-10-05 at 5 45 40 am

### CODE REVIEW

**Comment by rdbartlett** [comment]
Dear James. Please leave some jobs for everyone else. You are writing all the code.

**Comment by robguthrie** [comment]
sokay with me. plenty more work to do

**Comment by rdbartlett** [comment]
FYI James I just pushed up a little a11y improvement. I wonder if we should override the %i directive so we don't have to specify `aria-hidden: 'true'` all the time.

**Comment by robguthrie** [comment]
great idea.

**Comment by gdpelican** [comment]
@rdbartlett I pulled those aria changes out in favor of Rob's shiny new directive here: #2543

**Pull request merged**
