### PR TITLE
New vote webhook

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by robguthrie** [comment]
cool to have a SiteColors module.

**Comment by gdpelican** [comment]
Hmm.. I'm not sure why this passed under our repo, but not theirs... it seems like travis isn't setting the Chargify environment variables correctly under their remote... which is distressing because it would mean that basically no one can get tests to pass..

I'll have to sit down at some point and ensure we're not relying on those ENV variables for those tests, that it's got a default in secrets.yml or something.

**Comment by gdpelican** [comment]
Okay, here's the culprit:
http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

Solution is to not have those tests rely on ENV; I'll twiddle that up now.

**Comment by gdpelican** [comment]
(FYI @juliagra)

**Comment by robguthrie** [comment]
Seems like using Rails.application.secrets and the secrets.yml is a good
way to centralise all the configuration and defaults.

**Comment by gdpelican** [comment]
Closing; we'll get the other one merged in.

**Pull request closed without merging**
