### PR TITLE
locale update... slight format change with node yamlification

### PR DESCRIPTION
**Pull request by s01us**
some minor updates,
a massive format consolidation because now using a node yaml exporter

notice multi-line is being output with newline `\n` characters, need to test that's fine

### CODE REVIEW

**Comment by s01us** [comment]
multiline check

```yaml
en:
    start_discussion_html:  |
      <p>When you start a discussion, make sure the title conveys the topic succinctly.
      Use the Context Panel to give all the background information necessary for the
      group to have a productive and informed discussion.</p>
      <p>During the discussion, the Context Panel can be updated as new information
      comes to light. As well as clarifying the topic, you can use this space for
      sharing resources, summarising the discussion as it progresses, or outlining the
      decision-making protocols your group is using.</p>

bg-BG:
    start_discussion_html: "<p>Когато започвате дискусия, уверете се, че заглавието и предава стегнато темата и.\nИзползвайте и Контекст Панела за даване на всичката предварителна и допълнителна информация, необходима на вашата група за провеждане на продуктивна и информирана дискусия .</p>\n<p>По време на дискусията Контекст Панела може да бъде обновяван, ако се е появила нова информация. Освен за изясняване на темата, можете да използвате това място споделяне на ресурси, за обобщаване на дискусията по време на развитието и, за обявяване на механизъма за вземане на решение, който групата ви ползва.</p>\n"
```

en: 
selection_043

bg-BG:
selection_042

**yes good** :white_check_mark:

**Comment by s01us** [comment]
@robguthrie node yaml output package means a format change in yaml values 

In the comment above I show testing the only significant change I can see. ( how multiline now uses `\n\` ).  output in app is preserved :white_check_mark: 

Can you think of any potential problems that we should look for? 
I would appreciate if you spent 30 seconds looking at the sort of changes that have happened just as a sanity check.

other than that think this should be ready to go.

**Comment by s01us** [comment]
if you're on holiday still I can hit up James

**Comment by robguthrie** [comment]
Thanks @s01us nice to see the tools evolving. I think this is fine to deploy

**Comment by robguthrie** [comment]
I'll deploy shortly

**Pull request merged**
