### PR TITLE
Add animations to toast message

### PR DESCRIPTION
**Pull request by gdpelican**
Looks like this: https://drive.google.com/open?id=0B7rFWNdVhCDFNVFXUmp0N0JUUFU

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey @rdbartlett @mhjb , what do you think?

**Comment by rdbartlett** [comment]
I think it looks fine, and the movement will likely make the message more noticeable.

I was expecting to see it work like it does in the spec though, i.e. popping up like toast: https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-specs

**Comment by mhjb** [comment]
+1 for Material-style

**Comment by gdpelican** [comment]
Yeah I'm not planning on putting more Material into the app until we make a decision as a team that this is something we want to adopt more fully. Also the material components we have put in have been broken and not x-browser compatible.

**Comment by mhjb** [comment]
Interesting — sounds like a useful conversation to have. But here I'm just thinking imitate Material in how the animation looks, rather than actually adding a Material component

**Pull request merged**
