### PR TITLE
nice enough interface switcher

### PR DESCRIPTION
**Pull request by robguthrie**
TODO:
Only show "Try the new Loomio" to selected users.
Make sure the screen after that explains what the new Loomio is

In beta you will see:
image

Then:
image

Then:
image

Then:
image

### CODE REVIEW

**Comment by robguthrie** [comment]
@rdbartlett I've cut every corner I can and I wonder what you reckon.

It feels pretty nice to me

**Comment by rdbartlett** [comment]
i reckon it looks good enough to deploy and reconsider in sprint 10

**Comment by gdpelican** [comment]
I'd love to see 'switch back to Loomio beta' rather than 'old Loomio'

**Comment by rdbartlett** [comment]
sure

**Comment by robguthrie** [comment]
Ok.. I think "switch back" are the important words, happy to change that. I noticed we don't have a logo in the new version! I better put one in!

**Comment by robguthrie** [comment]
(or maybe @rdbartlett you want to draw up how the logo fits in there?)

**Comment by robguthrie** [comment]
Updated "Try it out " screen! @rdbartlett do you approve?

image

**Pull request merged**
