### PR TITLE
replace should == in tests

### PR DESCRIPTION
**Pull request by s01us**
I did a large regex find+replace on `.should ==` to update us to `expect(    ).to`

The motivation is so that people writing new specs have examples of good spec practice that they can confidently refer to. 

I hit specs + cuke steps,  lets see how the tests run

:poodle:

### CODE REVIEW

**Comment by s01us** [comment]
as a reference, here's the regex I used in sublime : 

**First round**
find:  `(?<=\s)(\w[\w\.]*)\.(?:should(\s)*==)`
replace:  `expect($1).to eq `

---

**fix the multi-line shoulds** 
find: `(?<=\s)(\w.*\.)\s*\n(\s*)expect\(`
replace:  `expect($1\n$2 `

---

**fix up other cases which have spaces, ignoring commented out cases**:

find: `^(\s*)([^\#\s\n].*)\.(?:should(\s)*==\s*)`
replace: `$1expect($2).to eq `

**Comment by rdbartlett** [comment]
You are a golden god

**Comment by robguthrie** [comment]
Wow. This is amazing. Really helpful. Hope you get the time to get this ready for merge

**Comment by denjello** [comment]
@s01us : "be_true ain't a thing" is probably the coolest thing I've heard all week.

**Comment by gdpelican** [comment]
I think they changed it in the rspec 2.99 -> 3.0 upgrade? (discussion [here](https://github.com/rspec/rspec-expectations/issues/283)) 

I personally think 'truthy' is one of the worst words ever, but `.to eq true` should be fine.

**Comment by s01us** [comment]
went with `be true` which as i understand it is the same as `== true`

**Comment by s01us** [comment]
all squashed + READY @gdpelican

**Comment by gdpelican** [comment]
Keep on :truck:ing!

**Pull request merged**
