### PR TITLE
Help page

### PR DESCRIPTION
**Pull request by HSalmon**
Hey @s01us I know you said you were up for a QA, as did you @rdbartlett. I think my eyes have been looking at this for way too long so would appreciate some feedback if that's all good. Ugly contents I know - interim step, will need some work. Suggestions welcome. Thanks!

### CODE REVIEW

**Comment by rdbartlett** [comment]
Hey @robguthrie Hannah's fixed the ToC now - I reckon it looks sweet. 

image

I have lots of ideas for the next iteration but I'm thinking we should just deploy now and then get to work on the next version. What do you reckon? Not in a huge hurry - happy to chat before merge :)

**Comment by robguthrie** [comment]
That looks really good! is it resize friendly/responsive? either way...
it's fine with me

**Comment by rdbartlett** [comment]
Yes! Works great on all screens

**Comment by rdbartlett** [comment]
Hold fire on this pls. Want to get everyon eup to speed before we deploy.

**Comment by gdpelican** [comment]
What's the next step for this thing? Looks like it needs a little merge conflict love, but I'd be keen to merge and move on to iteration 2 if it's ready and not breaking anything.

**Comment by HSalmon** [comment]
@gdpelican, I'm gonna make a few changes before we deploy. Rich and I talked about it today. But yeah. hoping to deploy v. soon

**Comment by HSalmon** [comment]
@rdbartlett, I think I've done what we agreed.

**Comment by rdbartlett** [comment]
This is beautiful! I think it is ready to go. I would love to hear what @robguthrie and @gdpelican think and then deploy today or tomorrow, then get feedback for round two.

Minor tweaks you might consider, but shouldn't get in the way of deploying: 

* adding another 20px of padding to the top of the `.help.anchor` headings to break up the sections a bit further
* add in a '^ Back to top' link after every section, with an anchor that brings you back to the table of contents

**Comment by robguthrie** [comment]
I don't think you need signoff from James or I. Just go ahead and merge
when you're ready, we'll support it/you as required.

I've had a brief look and I think it's a great piece of work.

**Comment by gdpelican** [comment]
Yeah merge dat. :hand:

**Comment by HSalmon** [comment]
Hey @rdbartlett, made those suggested changes (link at the bottom of each section etc), and squashed commits. Could we be deploy-ready?

**Comment by gdpelican** [comment]
Voosh! :dash:

**Pull request merged**
