### PR TITLE
Live update mark as read

### PR DESCRIPTION
**Pull request by gdpelican**
Am I nuts? I think this might be all we need to make live updating of read content work across tabs.

I'm going to spin up a faye server later hopefully and give this a spin.

### CODE REVIEW

**Comment by robguthrie** [comment]
yea nah this is what I've always thought was required. thing is you made message channels so great it's this easy now.

**Comment by robguthrie** [comment]
I wonder if we could use a light weight serializer for this..  something that just updates the specific attributes about reading discussions.

**Comment by gdpelican** [comment]
Whoa, so much yes.

**Comment by gdpelican** [comment]
I believe this should fix #2774 as well, the issue being that we're marking things as read in the DB when we create a comment, but not telling the client.

**Comment by robguthrie** [comment]
Yea it sure will. Are you happy to make a discussion_marked_as_read_serializer before we merge this?

**Comment by gdpelican** [comment]
Should be already in there as Simple::DiscussionSerializer

**Comment by robguthrie** [comment]
Arrr cool. Happy to merge this when you're happy.

**Pull request merged**
