### PR TITLE
Fixes Syntax Error on Group View

### PR DESCRIPTION
**Pull request by gbrego**
Hello, 

I have been keep up with Loomio Development.

I think I have found some syntax error on Master Code.

Please revise, comment and accept my pull request (if you want)!

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey @gbrego, thanks for the PR?

Are you experiencing an error page when trying to view a group?

**Comment by gbrego** [comment]
Yes, I'm experiencing syntax error on groups and discussions, as the screenshot you may see below

loomio_error

**Comment by gbrego** [comment]
@gdpelican thanks answering.

Yes I'm experiencing errors on group and discussions (it can be seen below)
loomio_error

**Comment by robguthrie** [comment]
Hi @gbrego, your patch is kind of interesting. We are not having problems with this part of the code, indeed if we were, our site would be very broken.

I cannot understand why you would be experiencing a problem with the code, or why your changes make any difference.

I'm going to close this pull request for now, we don't need this. But I do welcome your contribution, and thank you for taking the time to do this. I hope you enjoy using Loomio and maybe can contribute more in the future.

**Comment by gbrego** [comment]
@robguthrie  

I've found the cause of the error.

I was using ruby-2.2.0-preview (installed using homebrew) when I changed to ruby-2.2.0 it solved itself.

thanks for answering my Pull Request

**Pull request closed without merging**
