### PR TITLE
Fix for issue #2120, update outcome of a proposal

### PR DESCRIPTION
**Pull request by zacharystenger**
Changed ``params: params`` to ``params: permitted_params.motion`` in ``MotionsController#update_outcome``  
I've tested it and it works.

### CODE REVIEW

**Comment by gdpelican** [comment]
Great, thanks @zacharystenger 

Would you mind writing a test for this? Should be something in `motions_controller_spec.rb` along the lines of

```
context "updating a motion's outcome" do
  it "updates the motion's outcome" do
    # ensure that the outcome is actually updated when we patch :update_outcome
  end
end
```

Thanks!

**Comment by zacharystenger** [comment]
Sure thing.

**Comment by gdpelican** [comment]
So ya know, the last step will be to squash up the commits on your branch into a single commit; there's a couple of methods for doing that here:

https://github.com/loomio/loomio/wiki/How-to-squash

Thanks again for your contribution :cool::balloon:

**Comment by zacharystenger** [comment]
Awesome, thanks for the tip.

**Comment by zacharystenger** [comment]
I wrote a test that fails with this bug and passes with my fix. But, I feel like I'm only testing that ``MotionService#update_outcome`` is called correctly and am not checking that the outcome is actually updated.  Any feedback would be great, I'm pretty new to Ruby on Rails and RSpec, thanks!  
In ``motions_controller_spec.rb`` I added this with the other let commands
``  let(:permitted_params) { stub_model(PermittedParams, motion: {outcome: 'new outcome'}) }``  

And added this test:
```
context "updating a motion's outcome" do
  it "updates the motion's outcome" do
    MotionService.should_receive(:update_outcome).with(:motion => motion, :params => permitted_params.motion, :actor => user)
    post :update_outcome, :id => motion.key, :motion => permitted_params.motion
  end
end
```

**Comment by gdpelican** [comment]
Hm, I don't see these changes in the current PR; could you push them up?

As you note, the other tests in that area are just testing that the service is called correctly. So perhaps we want another test in `motion_service_spec.rb` to match the `describe '.create_outcome` test?

**Comment by zacharystenger** [comment]
I created the service test and pushed both.  
Reading up on squashing now. My apologies for the messy PR, future ones will be cleaner.  Thanks for your patience and help!

**Pull request closed without merging**
