### PR TITLE
Marking recently created items as read

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
This is ready for a look @robguthrie @HSalmon; I feel pretty good about it, but still need to do a smoke test (/ write an e2e maybe)

**Comment by robguthrie** [comment]
Wow. This looks really nice. The only quibble I have is the + 1.second .. Can't we use the exact created at?

**Comment by gdpelican** [comment]
Hm, I couldn't get that to work, but looking at it again I'm going to try going in and tweaking the `viewed!

**Comment by gdpelican** [comment]
Okay, I did a little refactor of the discussion reader stuff within events, which were a bit all over the place.

I ended up writing a `author_thread_item!` method on discussion reader, which encapsulates participating in a thread, viewing the item you just creating, and setting the volume to loud if necessary (all things we've been doing in chunks, sometimes in the event#publish method, sometimes in the service.)

**Comment by robguthrie** [comment]
This is wonderful work. Please squash and we can deploy!

**Pull request merged**
