### PR TITLE
Initial a11y language tweaks

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
[Relevant Trello card](https://trello.com/b/skuMQvLJ/loomio-sprint-board)

**Comment by HSalmon** [comment]
@robguthrie, @rdbartlett

**Comment by rdbartlett** [comment]
:+1: thanks Hannah, looks good to my reading

**Comment by robguthrie** [comment]
I'm not super happy with the language. i'll update with something in 20
minutes

**Comment by HSalmon** [comment]
@robguthrie, can we merge this and make a separate card? Or do you want me to update this PR?

**Comment by robguthrie** [comment]
yea we can merge for now. The changes I've got a reasonably big. Thanks @HSalmon

**Pull request merged**
