### PR TITLE
Remove vote buttons on closed proposals

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
@robguthrie, fix for issue @rdbartlett alerted us to

**Comment by robguthrie** [comment]
Is there an existing e2e test that we could update to include a test for this bug we're fixing?

**Comment by HSalmon** [comment]
Expectation added @robguthrie

**Comment by HSalmon** [comment]
@robguthrie, can we merge this?

**Comment by robguthrie** [comment]
Thanks for the reminder, @HSalmon

**Pull request merged**
