### PR TITLE
Add margin to motion icons in the list of votes

### PR DESCRIPTION
**Pull request by jakub-**

### CODE REVIEW

**Comment by jakub-** [comment]
Before:
before

After:
after

**Comment by robguthrie** [comment]
Looks good. Do you think we need to do any cross browser/platform testing? IE: will this look fine on mobile and desktop?

**Comment by rdbartlett** [comment]
It's fine cuzzy. Thanks Jakub!

On 6 February 2015 at 14:59, Robert Guthrie <notifications@github.com>
wrote:

> Looks good. Do you think we need to do any cross browser/platform testing?
> IE: will this look fine on mobile and desktop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/pull/1871#issuecomment-73168647>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>

**Comment by gdpelican** [comment]
Hm, this makes me a little nervous. Why was that line there but commented out?

**Comment by robguthrie** [comment]
No idea.. but I'm happy to go ahead with this.

**Comment by gdpelican** [comment]
Thanks @jakub- !

**Pull request merged**
