### PR TITLE
Style feedback card

### PR DESCRIPTION
**Pull request by AaronThornton00**
Hey peeps just a trial with this one.

I know @rdbartlett has already voice some concerns. Which is fair enough, just trying to clear my list. Have a look and close it if you don't think it is an improvement.
(If you give it enough lift it does not look like it is a component of the app)

- More depth to separate it from app
- Rounded corners to fit with app styling
- More emphasys on Feedback
- Simplify text on switch link
- Color a correctly
- Trim unused width so it doesn't get in the way

Before:
screenshot 2015-08-09 15 11 34

After:
screenshot 2015-08-09 15 02 22

### CODE REVIEW

**Comment by rdbartlett** [comment]
:+1:

**Comment by rdbartlett** [comment]
Hey @AaronThornton00 I like this - one question: did you forget to commit the changes to client.yml?

I was going to suggest if we're changing the label to "Back to beta", we should keep that language consistent with the "Switch back to old Loomio" on the angular switch-off screen and the "Switch back to the old Loomio" on the angular switch-on screen.

**Comment by AaronThornton00** [comment]
@rdbartlett hey bro feel free to change any of the copy, 'back to beta' was just a concise idea.  You can skin it how you wish.

**Comment by rdbartlett** [comment]
I'm just confused because the screenshot differs from the PR

**Comment by AaronThornton00** [comment]
Yeah sorry, I must have snap shotted the before after making the change to the yml file.
You can just look at master for a true comparison.

**Pull request closed without merging**
