### PR TITLE
Add verbose proposal hover timestamp

### PR DESCRIPTION
**Pull request by JonathanWThom**
[Issue #4319](https://github.com/loomio/loomio/issues/4319)

hover

### CODE REVIEW

**Comment by JonathanWThom** [comment]
Hope this covers it! Please let me know if there's anything I can change.

**Comment by gdpelican** [comment]
Hm, it seems good to move the filter into the view, but I'd be surprised if this actually changed the functionality?

Are we looking for `{{ time | exactDateWithTime }}` here?

**Comment by JonathanWThom** [comment]
Correct - you'll see that `ng-attr-title` is now set to `{{ time | exactDateWithTime }}`, so that the hover state shows the verbose time. `translate-value-time` is `{{ time | timeFromNowInWords }}`since I assumed that you wanted the actual shown text (e.g. "closed 7 months ago") to stay the same. 

Maybe you didn't - or maybe I'm confused!

**Comment by gdpelican** [comment]
Ah, right you are! Sorry for not scrolling past the fold. This looks good to me.

**Comment by JonathanWThom** [comment]
Cool! My first open source contribution. Neat project you have here - thanks for letting me chip in.

**Pull request merged**
