### PR TITLE
Updates on Translations

### PR DESCRIPTION
**Pull request by gbrego**
Hello Loomio Team, 

This is a simple commit for a message that was not included on languages YML files.

Thanks in advance.

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey, thanks @gbrego! Surprised we haven't caught this one before.

Hey @mixmix, is it ok to merge the pt-BR translations like this, or will that muck with Transifex somehow?

**Comment by robguthrie** [comment]
@mixmix really need you to reply to us.

**Comment by mixmix** [comment]
awesome catch @gbrego 

---

Hey this is safe to merge. 
the pt-BR.yml file will get over-written when we update, it will need to be changed in Transifex. 
Respectfully, we need to all understand this simple idea so that I'm not a hold-up when I'm away for a conference / having a weekend. :heart:

**Comment by robguthrie** [comment]
For clarity @gdpelican: Yes, any updates to non 'en' locales will be overwritten.

**Comment by gdpelican** [comment]
That's fine, I just wanted to make sure that we wouldn't have to deal with
a merge conflict or something down the line for committing to non-en files.
I'll put it in the knowledge bank.

**Pull request merged**
