### PR TITLE
Angular sign in

### PR DESCRIPTION
**Pull request by gdpelican**
Hey this totally works!

### CODE REVIEW

**Comment by gdpelican** [comment]
But of course this has to be reviewed and go in after beta is decommissioned.

**Comment by robguthrie** [comment]
did you get oauth support in there?

**Comment by gdpelican** [comment]
Yep

**Comment by gdpelican** [comment]
Looking ahead a bit to getting this one in:

The major change here is that, since the user can now change within a single angular session, it needs to be a method (`User.current()`), rather than a static variable (`CurrentUser`). Seem like ok naming @robguthrie?

**Comment by robguthrie** [comment]
Hrrmm.. if you're happy with it. Seems a bit weird , but also practical, to
put current user into the User model like that.

**Comment by gdpelican** [comment]
That's why the naming's weird; I renamed `CurrentUser` -> `User`, which is
different from `UserModel`. Maybe it should be called something else like
`Session.user()`?

**Comment by robguthrie** [comment]
Session.user() seems good to me.

**Pull request closed without merging**
