### PR TITLE
Fix Facebook OAuth2 signin not working

### PR DESCRIPTION
**Pull request by soundasleep**
Resolves 'found unpermitted parameter: Facebook'
Resolves 'found unpermitted parameters: first_name, last_name, verified'

### CODE REVIEW

**Comment by robguthrie** [comment]
Thanks @soundasleep! Awesome to have a PR from you.

Happy to merge this in now. How did you find/produce those issues?

**Comment by soundasleep** [comment]
I found them just in a fresh install and connecting to the Facebook OAuth2. Maybe it's their new Graph 2.0 API? I really don't know.

**Comment by rdbartlett** [comment]
Oh yeah I remember ignoring some email about important changes to the Graph 2.0 API...

Thanks for the PR @soundasleep :star2: :chart_with_upwards_trend: :v:

**Comment by gdpelican** [comment]
Awesome, thanks @soundasleep!

**Pull request merged**
