### PR TITLE
Add group members card to thread page

### PR DESCRIPTION
**Pull request by HSalmon**
[Trello card](https://trello.com/c/FGgfusAj/1921-add-group-members-card-to-thread-page)

screen shot 2016-09-14 at 12 56 13 pm
screen shot 2016-09-14 at 12 55 58 pm

### CODE REVIEW

**Comment by robguthrie** [comment]
nice! tests should start passing if you refresh the branch

**Comment by gdpelican** [comment]
Looks fine to me 🍏

**Comment by gdpelican** [comment]
Oops!

**Comment by mhjb** [comment]
How comes no normal QA process on this one? 

I've a hunch this isn't going to do what users expect it will … I think I'd expect it to in some sense invite a person into the discussion.

**Pull request merged**
