### PR TITLE
stop tracking users!

### PR DESCRIPTION
**Pull request by fauno**
this pr removes tracking users ip addresses and login times.  i realize you may not want to merge this, but i'm just leaving it here for other forks to use :)

also if you're using nginx+passenger, you can protect users with this [nginx.conf snippet](https://github.com/fauno/nginx-config/blob/develop/nginx.conf#L40)

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm... I pretty much agree that we don't really _need_ to be tracking ip address, but I think sign_in_count and last/current_sign_in_at are pretty low-damage tracking stats which are a key part of our analytics. Thoughts @robguthrie @rdbartlett?

**Comment by rdbartlett** [comment]
We've used the ip tracking to block spammers. So yeah I think we need that
until there's an alternative solution for the spam problem.

**Comment by gdpelican** [comment]
Yeah fair enough.

**Comment by fauno** [comment]
"Richard D. Bartlett" <notifications@github.com> writes:

> We've used the ip tracking to block spammers. So yeah I think we need that
> until there's an alternative solution for the spam problem.

are those spammers automated bots or just trolls?

-- 
http://endefensadelsl.org

**Comment by rdbartlett** [comment]
I haven't looked into it really closely, but I think they are bots. Rob
will have a better idea.

**Comment by gdpelican** [comment]
Going to close this for now, but thanks for the heads-up around this, @fauno. Going forward we'll be sure to be very transparent about what information we're tracking and why, and to provide some instructions for other instance owners around how to stop tracking that information if they want to.

**Pull request closed without merging**
