### PR TITLE
Explore page

### PR DESCRIPTION
**Pull request by gdpelican**
Merge in final fixes to explore page

### CODE REVIEW

**Comment by mhjb** [comment]
Now that it's live I've got a bit of feedback — but happy to wait for the appropriate time to share it…

**Comment by gdpelican** [comment]
@mhjb did this feedback ever get shared? I'd be keen to get @HSalmon a list of things for the explore page.

**Comment by mhjb** [comment]
I put it here https://trello.com/c/pmkgdMdG/1455-explore-page-next-iteration
but Richard archived it

**Comment by mhjb** [comment]
p.s. I can't believe how fast the search is on that page

**Comment by HSalmon** [comment]
Why was it archived @rdbartlett?

**Comment by rdbartlett** [comment]
Whoops overzealous clean up. Restored :)

**Pull request merged**
