### PR TITLE
Don't display slash when using search shortcut

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
I don't want to merge this yet; I think the behaviour's still a little erratic.

**Comment by robguthrie** [comment]
hey did you see the link about html keybindings? I think it will cover this kind of case without JS

**Comment by gdpelican** [comment]
Hm, I did have a look; I was a little sad that the way to activate access keys isn't consistent cross browser (firefox is CTRL+ALT+key, chrome is ALT+key, and we wouldn't be able to support not using modifier keys), so it's gotta be multiple key presses and different for different browsers.

Or I'm missing something maybe? I found the docs on the stuff kinda light.

**Comment by robguthrie** [comment]
I did not look closely enough.. I'll take your word for it.

**Pull request merged**
