### PR TITLE
A mobile app for Loomio [WIP]

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Any progress on this ?

**Comment by gdpelican** [comment]
It's not on my immediate radar, but we will be putting some real effort into this, likely early next year.

**Comment by jpdeplaix** [comment]
Hi, what is the status of this ? Of course I noticed it has been closed but is it still on your TODO list ?

**Comment by gdpelican** [comment]
As mentioned, it's not on the immediate radar, but we will be discussing options for tackling this in a way that fits with our strategy soon.

**Pull request closed without merging**
