### PR TITLE
richards great idea

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by gdpelican** [comment]
Looks good to meee!

Did you consider extracting out the `fa` class as well, so it could be

```
%icon{icon: 'plus', size: 'lg'}
```
?

**Comment by robguthrie** [comment]
no, but that's also a good idea.

**Comment by rdbartlett** [comment]
That is such a good idea.

**Comment by robguthrie** [comment]
merging this for now. Happy to improve it i -> icon later.

**Pull request merged**
