### PR TITLE
Pricing language tweaks; remove broken get in touch link

### PR DESCRIPTION
**Pull request by mhjb**
Before | After
--- | ---
image | image
image image | image
image | image

@rdbartlett

### CODE REVIEW

**Comment by mhjb** [comment]
whatcha reckon, @rdbartlett?
broken get in touch link makes me :''''(

**Comment by gdpelican** [comment]
Have to fix the tests before merge. I'll put this on my list.

**Comment by gdpelican** [comment]
Hooray tests are fixed!

**Comment by rdbartlett** [comment]
:+1:

**Pull request merged**
