### PR TITLE
Replace discriminate with setting inheritance_column

### PR DESCRIPTION
**Pull request by mvz**
This should work, right?

### CODE REVIEW

**Comment by robguthrie** [comment]
Yea, I believe it should. Try using
 
```
self.inheritance_column= :identity_type
```

and we'll see if the test suite passes

**Comment by mvz** [comment]
This is as far as I got. The big difference between `discriminator` and Rails' basic STI is that Rails stores the class name (e.g., `Slack` or `Identities::Slack`, and `discriminator` handles storing just `slack` with a lower-case `s`.

**Comment by robguthrie** [comment]
What's the motivation for removing discriminator?

**Comment by mvz** [comment]
I didn't understand how it was different from regular Rails STI. It still seems too tiny to be a separate gem, but I guess at least I understand what it does.

**Pull request closed without merging**
