### PR TITLE
proposal on right for larger screens

### PR DESCRIPTION
**Pull request by robguthrie**
Quick crack at it. Not bad.

image

### CODE REVIEW

**Comment by AaronThornton00** [comment]
Likey, likey (maybe more margin at top of both activity and proposal)

**Comment by AaronThornton00** [comment]
...or less in between proposal and activity

**Comment by rdbartlett** [comment]
Sometimes you just gotta do it.

**Comment by robguthrie** [comment]
One thing I really like about the current design is that the context panel is the same width as the activity panel. Not sure what I'll do about that if anything.

Anther thing I've noticed about this, is how much less vertical space we use when we fold the proposal up like this. Suddenly I feel like my fingers have a lot less work to do just to navigate.

**Comment by robguthrie** [comment]
The more things change, the more they stay the same huh?

**Comment by AaronThornton00** [comment]
I think they call it 'going full circle'

**Comment by robguthrie** [comment]
need to solve lintel

**Pull request closed without merging**
