### PR TITLE
use hypercubed/marked for markdown and clone discussion in discussion form

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by gdpelican** [comment]
Oh btford, how far from grace ye have fallen in Loomio land. :broken_heart:

**Comment by robguthrie** [comment]
haha

**Comment by rdbartlett** [comment]
Is this gunna fix the links? errbody is sad about the links :(

**Comment by robguthrie** [comment]
yes! those links that begin with http or https will be auto linked and open
in a new window

**Pull request merged**
