### PR TITLE
Thread comment responses by email

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
Have any thoughts on this one @robguthrie ?

**Comment by robguthrie** [comment]
yea, I think I'm ok with this. Let's give it a go. Thanks.

**Comment by robguthrie** [comment]
@gdpelican I think this broke reply to comment within the app!!

**Comment by robguthrie** [comment]
Update, I think it's related to drafts.

I'm getting: {"errors":{"parent":["Needs to have same discussion id"]}}

On some threads where I already have a draft saved

**Pull request merged**
