### PR TITLE
Translations update (ru, el,sv)

### PR DESCRIPTION
**Pull request by s01us**
hey @robguthrie this is ready. It's: 

- standard locale update
- inclusion of the new `.translation_stats.yml` in the app root, as [discussed previously](https://github.com/loomio/loomio/pull/1831)

### CODE REVIEW

**Comment by s01us** [comment]
@robguthrie I've had another good go at this with James, and can't deploy this without pulling from heroku or forcing the commit.

Can we make a time to troubleshoot what's going on with this deploy issue please?
maybe easy if we're sitting next to each other

**Comment by robguthrie** [comment]
Same advice as before: Force it and see what happens. Don't worry!

**Comment by robguthrie** [comment]
I thought we agreed on translation_coverage... which is more accurate than
"stats"

**Comment by s01us** [comment]
I'll try a force next time.
I think you said translation_coverage "or something".
If it's a problem i/you can change it, i don't mind

**Comment by robguthrie** [comment]
you're right, I probably did. I just thing that the file won't make much
sense to someone if it's called stats, but coverage really gets close to
what the information in the file is.

**Comment by s01us** [comment]
I honestly don't mind. I do have a preference towards acting and moving on.

If you'd like it changed, can you either ask me to do that or change it?

Xx

**Comment by robguthrie** [comment]
Heh, thanks please change.

**Pull request merged**
