### PR TITLE
removes white-space:nowrap to allow long option wrapping

### PR DESCRIPTION
**Pull request by juliencarnot**
should fix https://github.com/loomio/loomio/issues/4339

### CODE REVIEW

**Comment by robguthrie** [comment]
Thanks @juliencarnot. 
I would love to just merge this but I don't know what the effects are. 

Have you tested in some browsers, if so, which ones? I love screenshots if you're able to snap one.

We "officially" support ie11 (just barely), chrome, firefox and safari, from mobile (eg: iphone4 size) to desktop sizes. Usually we just resize the desktop browser window to test how things look.

Are you able to give some feedback on how this works? Sorry to be a drag

**Comment by juliencarnot** [comment]
Sure, I tested in Firefox and Chromium:
before:
before

after:
after

I don't have access to IE/Edge, but I'm pretty confident the text will wrap as it does for other polls!

**Comment by juliencarnot** [comment]
hum, hadn't notice the mess in the last column, will look into it and try to find a solution

**Comment by juliencarnot** [comment]
I think this is a better solution:
afterafter

background-size is supported by IE 11 and all modern browsers, it allows the text to use 100% of the space and not only of the bar.

**Comment by robguthrie** [comment]
thanks for sorting this out... really helpful. Yes, background-size has been the successful method for other bar charts.

**Comment by gdpelican** [comment]
Thanks heaps @juliencarnot :)

**Pull request merged**
