### PR TITLE
Add explanation for when position statement is too long and submit fails

### PR DESCRIPTION
**Pull request by HSalmon**
Addresses https://github.com/loomio/loomio/issues/2979

screen shot 2016-02-22 at 2 41 11 pm

Suggested improvements to language welcome

### CODE REVIEW

**Comment by gdpelican** [comment]
Looks good code-wise; what do you think of the language @mhjb @rdbartlett ?

**Comment by mhjb** [comment]
Great as is; but if you want it here's a language suggestion:

> Too many words! Short position statements let everyone quickly catch up on the proposal.

**Comment by rdbartlett** [comment]
This looks great and I don't want to offer any more opinions on the language.

**Comment by HSalmon** [comment]
Thanks for the engagement all!

**Comment by HSalmon** [comment]
Can we merge this @gdpelican?

**Comment by gdpelican** [comment]
I think we could take Matt's language suggestion and run with it.

**Comment by HSalmon** [comment]
Implemented @mhjb's language suggestion:
screen shot 2016-02-23 at 11 06 39 am

**Pull request merged**
