### PR TITLE
Add alert informing user of invalid filename

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
@robguthrie, @gdpelican and I paired - this seemed like the only thing to do at this stage

**Comment by robguthrie** [comment]
Thing is.. I wonder if the medicine is worse than the illness. I think that the majority of files that have already been uploaded with chars that would not be allowed by this validation don't have any problems. We might be bothering users unnecessarily?

**Comment by gdpelican** [comment]
I had that thought too. 
It was pretty amazing how bad the jquery-fileupload-rails gem was, documentation / sourcecode diving wise.

**Comment by robguthrie** [comment]
I'm really sorry guys!

**Comment by HSalmon** [comment]
We could just leave it - it's fixed in 1.0 and that's where people will be soon, right? I haven't had any enquiries about file uploads recently and maybe if I do get one I could just ask them to rename their file..? Not sure...I want us to help users but if this is more of a hindrance for them then maybe we should leave it

**Comment by gdpelican** [comment]
I think leaving this as is is likely the best pick for now; we're close enough to 1.0 that if we get more complaints about it, we can say 'try the new interface, it works there!'

**Pull request closed without merging**
