### PR TITLE
populate the new client.*.yml from existing translations

### PR DESCRIPTION
**Pull request by mixmix**
# a juicy treat !  

Why translate everything afresh when 42% is ripe for recycling! 
I've compared all the strings and mapped them into their new `client.*.yml` key-homes. 

### Notes 

I guess there's a small chance that the meaning of the phrases is different if the context has shifted, but I think it's a small risk.

As a record, here are the mappings of translations  that were conserved.  
In this hash : 
> key = old `*.yml` key, 
> value = new `client.*.yml` key

```ruby
{ 'simple_form.labels.user.email': 'memberships_page.email_label',
  'simple_form.placeholders.user.email': 'memberships_page.email_label',
  'common.email': 'memberships_page.email_label',
  'common.groups': 'profile_page.my_groups',
  'common.private': 'common.privacy.private',
  public: 'common.privacy.public',
  'common.public': 'common.privacy.public',
  save: 'common.action.save',
  edit: 'common.action.edit',
  like: 'common.action.like',
  unlike: 'common.action.unlike',
  cancel: 'common.action.cancel',
  'inbox.clear': 'inbox.clear',
  'common.unread': 'inbox.unread',
  'simple_form.labels.user.password': 'session_form.password_label',
  'simple_form.placeholders.user.password': 'session_form.password_label',
  password: 'session_form.password_label',
  'edit_comment.edit_comment': 'new_comment_item.context_menu.edit_comment',
  'notifications.header': 'group_page.notifications_label',
  'help.have_your_say': 'help_page.have_your_say',
  yes_position: 'vote_form.i_agree',
  abstain_position: 'vote_form.i_abstain',
  abstain_details: 'vote_form.i_abstain_details',
  no_position: 'vote_form.i_disagree',
  no_details: 'vote_form.i_disagree_details',
  block_position: 'vote_form.i_block',
  block_details: 'vote_form.i_block_details',
  'vote_form.submit': 'vote_form.submit_position',
  close_proposal: 'proposal_expanded.close_proposal',
  'helpers.submit.motion.create': 'proposal_form.start_proposal',
  'motion_form.edit.header': 'proposal_expanded.edit_proposal',
  'simple_form.labels.discussion.title': 'discussion_form.title_label',
  'simple_form.labels.motion.name': 'discussion_form.title_label',
  'email.proposal_closing_soon.closes_at': 'proposal_form.closes_at_label',
  'simple_form.labels.motion.description': 'proposal_form.details_label',
  details: 'proposal_form.details_label',
  group: 'discussion_form.group_label',
  'simple_form.labels.discussion.description': 'discussion_form.context_label',
  'footer.privacy': 'group_form.privacy.label',
  'common.privacy': 'group_form.privacy.label',
  positions: 'proposal_expanded.positions',
  'simple_form.no': 'proposal_position_no',
  'group_form.description': 'group_form.description_label',
  members: 'memberships_page.members',
  invite_people: 'group_page.invite_people',
  options: 'group_page.options_label',
  manage_members: 'group_page.options.manage_members',
  leave_group: 'group_page.leave_group.title',
  'common.following': 'group_page.notifications.following',
  'common.not_following': 'group_page.notifications.not_following',
  'groups.follow.not_following_details': 'group_page.notifications.not_following_details',
  profile: 'group_form.profile_label',
  name: 'memberships_page.name_label',
  'group_form.category': 'group_form.category_label',
  'group_form.visible_to.label': 'group_form.privacy.visible_to_members',
  'group_form.membership_granted_upon.label': 'group_form.privacy.membership_granted_upon',
  'group_form.discussion_privacy_options.private_only_html': 'group_form.privacy.private_discussions',
  'common.permissions': 'group_form.permissions.label',
  'group_form.what_can_members_do': 'group_form.permissions.helptext',
  'group_form.members_can.add_members': 'group_form.permissions.members_can_add_members',
  'group_permissions.c4': 'group_form.permissions.members_can_add_members',
  'group_form.members_can.create_subgroups': 'group_form.permissions.members_can_create_subgroups',
  'group_permissions.c10': 'group_form.permissions.members_can_create_subgroups',
  'group_form.members_can.edit_comments': 'group_form.permissions.members_can_edit_comments',
  'group_form.members_can.vote': 'group_form.permissions.members_can_vote',
  'group_permissions.c13': 'group_form.permissions.members_can_vote',
  coordinator: 'memberships_page.coordinator_label',
  remove: 'memberships_page.remove_member',
  delete_comment: 'new_comment_item.context_menu.delete_comment',
  confirm_delete_comment: 'delete_comment_dialog.question',
  'contact_page.labels.name': 'contact_message_form.name_label',
  'contact_page.labels.email': 'contact_message_form.email_label',
  'contact_page.labels.message': 'contact_message_form.message_placeholder',
  'help.coordinating': 'help_page.coordinating',
  'help.coordinating_details': 'help_page.coordinating_details',
  'help.different_ways': 'help_page.different_ways',
  'help.engaging_html': 'help_page.engaging_html',
  'help.example1_html': 'help_page.example1_html',
  'help.example2_html': 'help_page.example2_html',
  'help.get_in_touch': 'help_page.get_in_touch',
  'help.get_in_touch_description_html': 'help_page.get_in_touch_description_html',
  'help.getting_started': 'help_page.getting_started',
  'help.getting_started_description': 'help_page.getting_started_description',
  'help.getting_the_most': 'help_page.getting_the_most',
  'help.have_your_say_details_html': 'help_page.have_your_say_details_html',
  'help.have_a_discussion': 'help_page.have_a_discussion',
  'help.have_a_discussion_description': 'help_page.have_a_discussion_description',
  'help.help': 'help_page.help',
  'help.how_it_works': 'help_page.how_it_works',
  'help.invitation_html': 'help_page.invitation_html',
  'help.join_the_community': 'help_page.join_the_community',
  'help.images_and_text_formatting': 'help_page.images_and_text_formatting',
  'help.images_and_text_formatting_html': 'help_page.images_and_text_formatting_html',
  'help.keep_up_to_date': 'help_page.keep_up_to_date',
  'help.keep_up_to_date_html': 'help_page.keep_up_to_date_html',
  'help.make_a_decision': 'help_page.make_a_decision',
  'help.make_a_decision_description': 'help_page.make_a_decision_description',
  'help.prompt_people_details': 'help_page.prompt_people_details',
  'help.prompt_people_html': 'help_page.prompt_people_html',
  'help.positions_agree_description': 'help_page.positions_agree_description',
  'help.positions_abstain_description': 'help_page.positions_abstain_description',
  'help.positions_disagree_description': 'help_page.positions_disagree_description',
  'help.positions_block_description': 'help_page.positions_block_description',
  'help.start_discussion': 'help_page.start_discussion',
  'help.start_discussion_html': 'help_page.start_discussion_html',
  'help.start_proposal': 'help_page.start_proposal',
  'help.start_proposal_html': 'help_page.start_proposal_html',
  'help.video_id': 'help_page.video_id',
  'help.video_tutorial': 'help_page.video_tutorial',
  'help.video_tutorial_description': 'help_page.video_tutorial_description',
  'hint.context': 'hint.context',
  'hint.discussion': 'hint.discussion',
  'hint.invitation': 'hint.invitation',
  'hint.proposal': 'hint.proposal',
  'hint.vote': 'hint.vote',
  'pricing_page.intro': 'pricing_page.intro',
  'pricing_page.organisations': 'pricing_page.organisations',
  'pricing_page.organisations_examples': 'pricing_page.organisations_examples',
  'pricing_page.informal_groups': 'pricing_page.informal_groups',
  'pricing_page.informal_groups_desc': 'pricing_page.informal_groups_desc',
  'pricing_page.informal_groups_examples': 'pricing_page.informal_groups_examples' }
121/290 = 42% conserved
```

### CODE REVIEW

**Comment by s01us** [comment]
next steps: 

- take it for a spin, see if it breaks new front-end
- write a scripts for batching uploading to Transifex

**Comment by robguthrie** [comment]
I'd like to do a final name tweek pass on all our keys before we get locked into anything.. IE: Some time next week review all the names and namespaces together and be free to make any changes necessary.

But this is an awesome piece of work. Thank you for taking the initiative on this!

**Comment by s01us** [comment]
yeah no worries
we're not locked in yet. Also, what I've built and will build will make it easy to change who swaths of keys in the future

**Comment by s01us** [comment]
interesting - looks like fallbacks aren't a thing in the current translation setup

**Comment by robguthrie** [comment]
just what I always wanted. xxxxxxxxxxxxxxxxx

**Comment by robguthrie** [comment]
we're using a rather out of date version of angular translate...

**Comment by gdpelican** [comment]
Closing in favor of #2300

**Pull request closed without merging**
