### PR TITLE
Add new pricing page

### PR DESCRIPTION
**Pull request by HSalmon**
screen shot 2015-08-26 at 4 05 48 pm

### CODE REVIEW

**Comment by HSalmon** [comment]
@rdbartlett, @mhjb - thought? tweaks?

**Comment by rdbartlett** [comment]
wow it looks pixel perfect!

**Comment by rdbartlett** [comment]
Is there a reason for not using bootstrap columns? It would be nice if this were mobile responsive.

**Comment by rdbartlett** [comment]
Reminder: when this gets deployed make sure we record the id of the latest parent group.

**Comment by robguthrie** [comment]
Bootstrap columns were harder than floats in the end. This is mobile responsive, the floats fold under each other.

**Comment by mhjb** [comment]
Beaut. Possible to on mobile have Gift last?

**Comment by mhjb** [comment]
Sorry - ignore that comment.

**Comment by robguthrie** [comment]
will do!

**Comment by gdpelican** [comment]
I guess this will become clear as the onboarding flow designs are teased into existence, but how will this work for an angular user?

**Comment by mhjb** [comment]
Angular users' new group form links to that pricing page too. Well it
intends to — the link is broken.

[image: Inline images 1]

**Comment by robguthrie** [comment]
Great question James. I was imagining that we rebuild it in angular. This
is a page for people who have not yet signed up.

**Pull request merged**
