### PR TITLE
Move to simpler single pane sidebar

### PR DESCRIPTION
**Pull request by gdpelican**
For #3598 

I've just removed the additional scroll area from the sidebar, which should make it much simpler to edit going forward.

### CODE REVIEW

**Comment by robguthrie** [comment]
Do we need to do some browser compatibility testing on this?

I don't get this PR right now.. I see the sidebar is now one panel.. What's the difference with this?

**Comment by gdpelican** [comment]
Er, this is the implementation of your suggestion here:
https://github.com/loomio/loomio/issues/3598

With one panel, we don't have to deal with crazy scrolling issues.

**Comment by robguthrie** [comment]
Heh. Thanks James. The thing I'm finding confusing about this is that the sidebar already operates as one panel for me in chrome.

As this screenshot kind of suggests:
image

**Comment by gdpelican** [comment]
Yeah. The hope is that this operates the same on chrome, but works on Firefox because there aren't multiple scrolling divs.

**Comment by robguthrie** [comment]
just updated/merged this against master.. I'll deploy soon

**Comment by gdpelican** [comment]
Alright to merge this @robguthrie ?

**Comment by robguthrie** [comment]
yeah! 🍏

**Pull request merged**
