### PR TITLE
tweaks

### PR DESCRIPTION
**Pull request by mhjb**
@rdbartlett pls review

Before | After
------------ | -------------
image | image
image | image
image | image
image | image

### CODE REVIEW

**Comment by rdbartlett** [comment]
what's the last one?

**Comment by rdbartlett** [comment]
Oh, right, the `button + button` margin. That was in there to make the spacing good on any modals that have 2 adjacent buttons. But we don't have any of them anymore eh?

**Comment by mhjb** [comment]
I looked and couldn't find any

**Comment by rdbartlett** [comment]
all good then

**Comment by mhjb** [comment]
ready when you are @robguthrie

**Pull request merged**
