### PR TITLE
UX upgrade for proposals / checks

### PR DESCRIPTION
**Pull request by gdpelican**
screen shot 2018-03-28 at 11 43 42 pm
screen shot 2018-03-28 at 11 43 56 pm
screen shot 2018-03-28 at 11 44 08 pm
screen shot 2018-03-28 at 11 44 22 pm
screen shot 2018-03-28 at 11 44 27 pm
screen shot 2018-03-28 at 11 44 41 pm

### CODE REVIEW

**Comment by robguthrie** [comment]
flipping great work!

Here it is on iphone 5
image

If I remove the min-width: 88px rule inherited from .md-button it looks like this:
image

Maybe you can add a `min-width:64px !important` to the appropriate class?

I'll give this a super quick user test now and get back to you.

**Comment by robguthrie** [comment]
Is it possible to animate the form when it appears? slide down or something? 

Otherwise I'm confident this will be an improvement

**Comment by gdpelican** [comment]
Alright this one is ready to go, with animation and tiny screen width fix. Permission to merge?

**Comment by robguthrie** [comment]
👍

**Pull request merged**
