### PR TITLE
update to rails 4.2.5.1

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by robguthrie** [comment]
@gdpelican any idea why these tests have decided to fail? it's crazy....

**Comment by gdpelican** [comment]
Er, no idea, that looks pretty effed to me. Maybe try updating the roadie gem?

**Comment by gdpelican** [comment]
Also maybe this?

https://twitter.com/samphippen/status/692029477774364675

**Comment by robguthrie** [comment]
@gdpelican this is failing on marked.js. Any ideas?

**Comment by gdpelican** [comment]
My first guess would be nvm version; checking travis.yml to make sure it's
using 4.2.6 might be good.

**Pull request closed without merging**
