### PR TITLE
Update group privacy language to reflect reality

### PR DESCRIPTION
**Pull request by HSalmon**
[Trello card](https://trello.com/c/qHUJr5wY/1158-3-member-visibilty)
[PR for update to help manual](https://github.com/loomio/user-manual/pull/23)

### CODE REVIEW

**Comment by rdbartlett** [comment]
Nice! I wonder if we should rename the transnational keys to force them to
be updated?

**Comment by HSalmon** [comment]
@rdbartlett, Nati could make the update maybe? @robguthrie, @gdpelican, I don't think this needs further attention, unless anyone wants to double check it.

**Comment by HSalmon** [comment]
Sorry, this is actually not finished at all!

**Comment by HSalmon** [comment]
Smoke test checklist:
1. Check members list is not visible to non-group members (for all Angular groups)
2. Check language on edit group form reflects that members list is not visible to non-group members (including when group is subgroup)
3. Check the above for beta
4. Check update to help docs is accurate: [PR for update to help manual](https://github.com/loomio/user-manual/pull/23)

**Comment by gdpelican** [comment]
:white_check_mark: Check members list is not visible to non-group members (for all Angular groups)
:white_check_mark: Check language on edit group form reflects that members list is not visible to non-group members (including when group is subgroup)
:x: Check the above for beta (I can see memberships for groups I'm not a member of in beta. For the edit form, beta doesn't say anything about who can see a group. It's not wrong, so not sure that we need to change that.)
:white_check_mark: Check update to help docs is accurate: PR for update to help manual

**Comment by HSalmon** [comment]
@gdpelican, when you say you can see memberships, what are the privacy settings for that? (I'll check as well). Also, What does this need to get sign off?

**Pull request merged**
