### PR TITLE
Add stories to marketing page

### PR DESCRIPTION
**Pull request by HSalmon**
[Trello card](https://trello.com/c/ON6rsMTN/954-5-display-stories-on-homepage)

screen shot 2015-11-18 at 3 08 01 pm

### CODE REVIEW

**Comment by robguthrie** [comment]
@rdbartlett look at this. Tell us what needs to be improved!

**Comment by robguthrie** [comment]
@mhjb do you have any designy feedback on this?

**Comment by rdbartlett** [comment]
Awesome!! 

Images need to be cropped to be the same dimensions. Wordpress will serve you cropped images like this: https://loomio.files.wordpress.com/2015/10/17-tory-st.jpg?w=250&h=155&crop=1'

Or you can CSS, specify the size of the div, set the background to the src, and use `background-size: cover` to make it crop nicely.

**Comment by robguthrie** [comment]
note to ourselves: add cron job to update stories hourly

**Comment by rdbartlett** [comment]
Can we get this onto loomiotest plz?

**Comment by robguthrie** [comment]
yes!

**Comment by rdbartlett** [comment]
@robguthrie can you run the cron or whatever it is that we need to do to get loomiotest.org to display the stories?

**Comment by rdbartlett** [comment]
Cool, it's working now. 

I'm not super happy with the resolution of the images. It's kinda awkward because we want to balance low file size with nice aesthetics, taking the responsive layout into consideration. Currently on iPad it looks stink:

image

As an easy halfway solution, can we just change thumb_url so it is loading images at say 500x310? That looks like this:

image

Also notice the aspect ratio (500x310) is the same as what's used on the blog.

**Comment by rdbartlett** [comment]
(oops accidental close)

**Comment by robguthrie** [comment]
yes we can do that rich

**Comment by HSalmon** [comment]
image

**Pull request merged**
