### PR TITLE
meta google site verification

### PR DESCRIPTION
**Pull request by simontegg**
add google site verification to activate Web Master Tools for better marketing knowledge

### CODE REVIEW

**Comment by robguthrie** [comment]
Whoa @gdpelican this should have been in a ENV variable. We can't have other people knowing a site verification token.

**Comment by gdpelican** [comment]
Even if it was in ENV, it'd just show up in the markup on the client side, so I don't think we can keep it a secret.

**Comment by gdpelican** [comment]
Er. except the marketing page doesn't get rendered ever for third parties. So I'll waffle again and say it's good.

**Comment by robguthrie** [comment]
yaaaa...ok

**Pull request merged**
