### PR TITLE
Fix thread actions spacing

### PR DESCRIPTION
**Pull request by gdpelican**
This style is making our thread view look like crap and, after searching for a reason for it to be there for some amount of time, I couldn't find one. So let's ditch it. :tada:

### CODE REVIEW

**Comment by rdbartlett** [comment]
Actually this is a namespacing error. There are two different uses for .thread-actions. It's on the bottom of comments (which this css breaks) and on the carets on the top right of cards (which this css fixes).

**Comment by gdpelican** [comment]
Can the fix be removing the `thread-actions` class from the events in the thread then?

**Comment by robguthrie** [comment]
I think thread-actions is a back block name for anything on the
thread-items. Can we remove all thread-actions mentions from there?

**Comment by robguthrie** [comment]
back = bad

**Comment by robguthrie** [comment]
I'm having a bit of a tidy up of this code... it's from our sorta BEM days and it's hurting now. Gimmie 20 mins

**Comment by robguthrie** [comment]
Ok I've updated this a bit.. more correct BEM naming.. but not sure how accurate it is:
image

**Comment by gdpelican** [comment]
Whoa looks pretty great to me, although I think the vote icon could still use a little bottom padding to match the spacing on the other event types

**Pull request merged**
