### PR TITLE
Add proposal closed activity item

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
@robguthrie, @gdpelican, here is this ticket: https://trello.com/c/aeol51RE/595-activity-item-when-the-proposal-closes

**Comment by gdpelican** [comment]
Looks pretty good to me at a glance. Is there a way to make existing closed motion events show up, or no?

**Comment by HSalmon** [comment]
@robguthrie, is this one good to go? I can make another ticket for the other activity items

**Comment by robguthrie** [comment]
√

**Pull request merged**
