### PR TITLE
move to ruby 2.2.3 and update gemfile

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by gdpelican** [comment]
Excite for ruby 2.3 soon!

**Comment by robguthrie** [comment]
Personally I'm really excited to see if we can run upon Rubinius one day.
What is it about ruby 2.3 that excites you?

**Comment by gdpelican** [comment]
No massive wins; I don't care about the safe navigation operator so much, but Hash/Array#dig is cool, and Hash#select_values is cool, and greb_v could be cool.

**Comment by robguthrie** [comment]
Thanks. I agree with that!

**Pull request merged**
