### PR TITLE
Fix urls

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by robguthrie** [comment]
This is going to take another hour or two to fix up. It fixes a bug whereby discussions would not be linked to the correct subdomain.

**Comment by robguthrie** [comment]
latest test shows that updating a discussion is broken under this.. need to investigate.

**Comment by gdpelican** [comment]
What's the status on this @robguthrie? Did this make it into master in another form already?

**Comment by robguthrie** [comment]
nope.. there is one bug to fix - updating discussions is broken

**Pull request closed without merging**
