### PR TITLE
Red notifications badge, border around both badges

### PR DESCRIPTION
**Pull request by mhjb**
before
=====

image

after
====

image

### CODE REVIEW

**Comment by mhjb** [comment]
@rdbartlett

**Comment by gdpelican** [comment]
I am a fan of the badge borders, but am not a fan of the red. Feels very
unharmonious with the rest of the interface to me.

**Comment by rdbartlett** [comment]
Yep borders are nice, but why the red? In Loomio, red means block or
delete.

**Comment by mhjb** [comment]
Read means important

image

image

image


This PR stimulated by watching users not noticing their Loomio notifications.

**Comment by rdbartlett** [comment]
I abstain.

**Comment by gdpelican** [comment]
I'm maintaining my disagree. We can up the visibility of notifications with an animation on update and with not having two versions of notifications on opposite sides of the screen, but having yellow, blue and red on the navbar makes this looks really bad imho.

**Comment by robguthrie** [comment]
feels like da cops

**Comment by gdpelican** [comment]
Gonna merge this in without the red for now, could be a good thing to circle back on a notification color scheme strategy at some point... Discourse has a rainbow of notification colors and I think they're a little tough to grok, but maybe there's some color scheme out there that makes sense.

**Pull request merged**
