### PR TITLE
lets govern Spain together

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by rdbartlett** [comment]
QA and deploy when you're ready please

:fireworks: :post_office: :rocket:

**Comment by robguthrie** [comment]
waiting on tests and I'll deploy

**Comment by s01us** [comment]
such excite

**Comment by rdbartlett** [comment]
To demonstrate how it works, I added all the groups with "podemos" in their name to a new network called "Podemos". (This is on a local copy of the database, not live on the web.)

Here's what a logged-out visitor sees when they visit the Podemos network page. It shows all the public threads in all of the groups in the network, sorted by most recent activity:

screen shot 2015-03-11 at 1 34 05 pm

And the groups list, sorted by size:

screen shot 2015-03-11 at 1 48 45 pm

Coordinators of groups can ask to connect their group to the network:

screen shot 2015-03-11 at 1 39 56 pm

And the requests are managed by a network coordinator:

screen shot 2015-03-11 at 1 41 00 pm

**Comment by denjello** [comment]
@rdbartlett wow.

**Comment by swergas** [comment]
woooo

**Comment by rdbartlett** [comment]
It's live...

https://www.loomio.org/n/podemos

**Pull request merged**
