### PR TITLE
[wip] Frontpage improvements

### PR DESCRIPTION
**Pull request by HSalmon**
[Trello card](https://trello.com/c/YH1EkKlp/1839-5-front-page-improvements)
PR on Loomio org plugin: https://github.com/loomio/loomio_org_plugin/pull/18

screen shot 2016-09-02 at 8 00 15 am

frontpage-mobile-menu-collapsed

### CODE REVIEW

**Comment by robguthrie** [comment]
wow that looks great!

**Comment by gdpelican** [comment]
+1!

**Comment by rdbartlett** [comment]
Nice one @HSalmon 

On mobile, can you make the menu 100% width, make the whole block clickable, and make sure each list item is at least as tall as a fat finger?

**Comment by rdbartlett** [comment]
and test for accessibility! :)

**Comment by HSalmon** [comment]
@rdbartlett, I did an accessibility sweep with the screen reader but I would appreciate someone else giving it a test - would you be up for it?

**Comment by rdbartlett** [comment]
Yes if I can get access to it without too much hassle

**Pull request merged**
