### PR TITLE
Upgrade Rails to 4.2

### PR DESCRIPTION
**Pull request by gdpelican**
Conflicts:
	Gemfile
	Gemfile.lock

### CODE REVIEW

**Comment by gdpelican** [comment]
We still have a few deprecation warnings to take care of, but the tests pass and the basic workflows (sign up, create a group, create a discussion, etc.) seem to work as advertised.

**Comment by jakub-** [comment]
@gdpelican Hey, cool that you're taking this over, sorry I hadn't responded, busy week!

**Comment by gdpelican** [comment]
Hey no worries. Well look forward to seeing you around again when time and motivation allow.

**Comment by gdpelican** [comment]
This is good to go. How do you feel about squashin' and upgrading to 4.2 today, @robguthrie?

**Pull request merged**
