### PR TITLE
dev doc: removes unnecessary npm install, adds yarn

### PR DESCRIPTION
**Pull request by juliencarnot**
After the [details](https://www.loomio.org/d/iZxd3o9f/common-errors-on-update-from-upstream) from @robguthrie

### CODE REVIEW

**Comment by robguthrie** [comment]
Good improvement thank you.
Not sure why it's conflicting rn.
Also a minor thing, I don't think try `gulp compile` again adds much, one could just try gulp dev again.

**Comment by gdpelican** [comment]
Thanks again for your work @juliencarnot !

**Comment by juliencarnot** [comment]
@robguthrie `gulp dev` still stalls after the compile-fast step on my install, but `gulp compile` works...

**Comment by gdpelican** [comment]
Hmmmm... I ddon't think gulp dev is stalling, rather it's running a watch
which will update your files automatically when you change them. I wouldn't
expect `gulp dev` to complete unless you manually kill it.

**Comment by juliencarnot** [comment]
That makes a lot of sense! Thanks for the explanation!

**Comment by robguthrie** [comment]
ah hah! now we all understand! :)

**Pull request merged**
