### PR TITLE
Fix export

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
Would love a smoke or thumbs up on this one @mhjb @robguthrie

**Comment by mhjb** [comment]
Still broke on production, and doesn't work on clone; is it live somewhere else?

**Comment by gdpelican** [comment]
Ah, I was thinking a local dev env check, but I can deploy to test if need
be.

**Comment by mhjb** [comment]
on local I get 

image

**Comment by gdpelican** [comment]
Hrm. Could you ensure the rails server's been restarted, ensure the branch
is correct, and give it another go?

**Comment by mhjb** [comment]
sorry; branch wrong; trying again

**Comment by mhjb** [comment]
works :)

**Comment by gdpelican** [comment]
Off it goes, then! I'll notify on deploy.

**Pull request merged**
