### PR TITLE
[not ready] first pass at cleaning up 2 column thread page

### PR DESCRIPTION
**Pull request by rdbartlett**
Pretty happy with how this is going. Thread page complete, next step is to bring all the other pages up to this spec and then remove

```
$main-max-width: 640px;
$medium-max-width: 767px;
$large-max-width: 960px;
```

### CODE REVIEW

**Comment by rdbartlett** [comment]
FYI @gdpelican this is where I got to with the 2 col thread page. I think it is pretty cool. 

I started trying to generalise this out to the group page but realised we actually want different behaviour. Group page right column should always be 320px.

So if you're happy, we can merge this now and come back to do the generalising job, or hold off merging until we've sorted out 2 cols everywhere. As you like :)

**Comment by gdpelican** [comment]
I don't necessarily think we need to generalize the two column thing, even long-term. The primary screens for me, even long term, would be

- Inbox / dashboard / wall
- Network-related stuff
- Group-related stuff
- Discussion-related stuff

And I reckon those will all likely deserve distinct layouts.

**Comment by robguthrie** [comment]
good call

**Comment by rdbartlett** [comment]
Alright this is all done now, I'm really happy with the result. Check it out @gdpelican.

Ready to go.

**Pull request merged**
