### PR TITLE
Custom oauth providers

### PR DESCRIPTION
**Pull request by gdpelican**
Port of #2172 to master repository

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey @soundasleep, I've got this all squashed and I think ready to go, but would love to do an end-to-end smoke test with some custom OAuth provider; any idea how I might do that quick/dirty/easy? :cookie:

**Comment by gdpelican** [comment]
Closing for now.

**Comment by soundasleep** [comment]
@gdpelican sorry for the delay in replying - I found using GitHub OAuth2 as a custom provider was a nice easy one to debug with :)

**Comment by gdpelican** [comment]
Sorry to dig up this old PR @robguthrie @soundasleep, but thought it might be interesting to note that ruby 2.3 has fixed the issue we were having with accessing nested hash data, with the #dig command:

```
hash = {
  user: {
    name: {
      { first: "James", last: "Kiesel" }
    }
  }
```

```
hash.dig(:user, :name, :first) # => "James"
hash.dig(:user, :address, :first) # => nil # doesn't error if the nest doesn't exist
```

Similar method works for Array as well.

**Comment by robguthrie** [comment]
That's really cool. Thanks James!

**Comment by drskullster** [comment]
So... Any chance we see progress on this in the near future @gdpelican ? I see that branch was deleted but I can't find any info on this. I'm really not familiar with Rails or Ruby but I can try to help.

Nb: for quick tests, Postman 2 now handles Oauth2 token generation.

**Comment by drskullster** [comment]
@gdpelican @robguthrie sorry to bother you with this, still no plan to implement this ?

**Comment by robguthrie** [comment]
@drskullster. Sorry no, it's not something our paying customers are asking for, and we have a survival strategy right now, which is to work on things that people are prepared to pay for.

**Pull request closed without merging**
