### PR TITLE
Don't pass nil user to comment service in griddler

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by gdpelican** [comment]
http://errbit.loomio.org/apps/56ef80443132390011000000/problems/57084ab8657272000e00001f

**Comment by gdpelican** [comment]
It occurs to me that we want to handle this from within the service, actually. But way more work at this point to go through every action and make sure there's a user of some kind trying to do it.

**Comment by robguthrie** [comment]
Acutally I don't think this is the right thing to do. It never makes sense
to create a comment as a logged out user (currently). And if we do this,
then the service returns false.. which is not really explicit behaviour.

Can we put a bang on the User.find_by so the response is a 404. I think
that makes more sense.

**Comment by gdpelican** [comment]
Service should raise an auth on `user.ability.authorize!(:create, comment)`, which will raise 403 unauthorized. I think that's more appropriate for this than 404 not found?

**Comment by robguthrie** [comment]
oh cool. Did not see that.

**Pull request merged**
