### PR TITLE
locales update: de, el, es, hr

### PR DESCRIPTION
**Pull request by mixmix**

### CODE REVIEW

**Comment by mixmix** [comment]
this is ready to go @robguthrie / @jamesmccann 
i'm not safe to deploy yet ... 
lets do a test sitting next to each other when you're next free Rob

**Comment by gdpelican** [comment]
I've had issues deploying recent with `./deploy.sh` as well; would be
really interested to hear what issues you're running into and if there's a
workaround.

**Comment by mixmix** [comment]
apparently the last 2 times I used deploy.sh it broke angular on
production.

rob suggested I try confirming things were working locally. I got some
errors re-installed things with npm... seemed to iron those out. angular
works apart from the dashboard, but not sure what that's about... as in
could be broken for everyone at the moment.

Probably next step is to go through `deploy.sh` and run everything line by
line and watch for errors. I don't remember seeing any last time i deployed
though

**Comment by mixmix** [comment]
@robguthrie can you merge and deploy this please ? 

cheers

**Pull request merged**
