### PR TITLE
Disallow manual text area resize

### PR DESCRIPTION
**Pull request by gdpelican**
@mhjb @rdbartlett Am I crazy for doing this?

For #2816

### CODE REVIEW

**Comment by mhjb** [comment]
Mind explaining your rationale?

**Comment by gdpelican** [comment]
Sure. The auto-expanding text area package means you can't resize vertically (it will only expand to the height of the text inside it). Messing with the horizontal size doesn't add much value, and more often than not looks like crap:

screen shot 2015-12-18 at 8 13 33 pm
screen shot 2015-12-18 at 8 13 51 pm

Thus... I'm not sure I can think of a good case for letting users resize their text areas.

**Comment by robguthrie** [comment]
arr thanks. I agree remove it if we have auto resize

**Comment by rdbartlett** [comment]
Sweet as

**Pull request merged**
