### PR TITLE
Markdown proposal

### PR DESCRIPTION
**Pull request by fauno**
Renders proposal texts as markdown :)

### CODE REVIEW

**Comment by robguthrie** [comment]
Thanks @fauno! This looks great! 

I'm pretty sure we can merge this in. I'm just going to see if @rdbartlett @HSalmon or @gdpelican have any comment.

**Comment by gdpelican** [comment]
Looks great to me :+1:

**Comment by rdbartlett** [comment]
Lovely. Do we need to consider any changes to thread-mailer or is that already covered/

**Comment by fauno** [comment]
:) what i didn't find was a way to render the outcome in the collapsed proposal for the new interface

**Comment by gdpelican** [comment]
Happy enough to merge this in, @robguthrie ?

**Comment by robguthrie** [comment]
yes!

**Pull request merged**
