### PR TITLE
inaugral loomio 1.0 translations!

### PR DESCRIPTION
**Pull request by mixmix**
schwam! 

:coconut:

### CODE REVIEW

**Comment by mixmix** [comment]
@robguthrie 

TREATS

**Comment by gdpelican** [comment]
Whoa, so great... the community's really been chugging along on this stuff.

Also amaze that github has no coconut emoji (╯°□°）╯︵ ┻━┻

**Comment by mixmix** [comment]
I wish. That's transifex intelligently copying exact phrase matches with
old translations.
But it'll certainly be a booster for any languages that actively translate
the new interface

**Comment by robguthrie** [comment]
wowo!!

**Pull request merged**
