### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by HSalmon**

### CODE REVIEW

**Comment by HSalmon** [comment]
screen shot 2016-02-25 at 4 10 04 pm

**Comment by HSalmon** [comment]
Addresses (hopefully): https://github.com/loomio/loomio/issues/3016

**Comment by gdpelican** [comment]
Hey @HSalmon I want to hold off on this one just a little while longer; I don't quite yet feel confident in it.

Looking at this, I'm not quite sure why there needs to be two different null checks, since our element looks like this:

```
        %span
          %span{ng-if: "onlyPrivacyEdited()", translate: "{{privacyKey()}}"}
```
(PS nested spans seems a bit fishy there :P)

So wondering if we actually need to check to see if this should appear in both `privacyKey()` and `onlyPrivacyEdited()`?

**Comment by HSalmon** [comment]
@gdpelican, double span thing is how we're doing the text for the other activity items. Can we pair on this at some point? Would like to get it merged because it's got the missing translation strings in it

**Pull request merged**
