### PR TITLE
Add deploy hooks for clone / testing

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by robguthrie** [comment]
what does this do James?

**Comment by gdpelican** [comment]
Nothing good. I've reverted it in master.

**Comment by gdpelican** [comment]
Also, I've set up all the CI stuff in a separate branch which I can build on travis separately from master so I don't have to muck about in master.

**Comment by robguthrie** [comment]
I don't want anything auto pushing to testing (I really like being able to
push whatever I want to testing, i dont mind if the tests are not
passing).. happy with auto test and push to clone.

**Pull request merged**
