### PR TITLE
Make modal widths consistent, update charater limit message for vote form

### PR DESCRIPTION
**Pull request by HSalmon**
Addresses: https://github.com/loomio/loomio/issues/3874

screen shot 2016-11-21 at 1 47 22 pm

### CODE REVIEW

**Comment by gdpelican** [comment]
I think this is going to require a little more thought. What about these modals?
screen shot 2016-11-21 at 10 02 24 am

screen shot 2016-11-21 at 10 03 02 am

screen shot 2016-11-21 at 10 04 26 am

**Comment by HSalmon** [comment]
@gdpelican, I understand what you're saying but personally I'm not sure that it matters for some of the modals that were smaller before. I spent some time on it yesterday and couldn't get it to work the way I wanted it to. Do you wanna have a stab? Or provide some additional guidance?

**Comment by gdpelican** [comment]
I was able to size particular modals by adding an `%md_dialog` element to the root of the template.

So for the discussion form, I could do

```
%md_dialog.discussion-form
  %form{...}
```
and in the css
```
.discussion-form {
  width: 60%; // or whatever's right for that modal)
}
```

Does that help?

**Comment by HSalmon** [comment]
Ok, @gdpelican, I just fixed the vote-form and removed the blanket md-dialog width:

fix-vote-form-width

**Comment by gdpelican** [comment]
Cool, looks good to me.

If you feel emboldened you could do that same for the discussion form (which tweaks out when you go from 'edit' to 'preview') in another PR, or I'll grab it sometime next week.

**Pull request merged**
