### PR TITLE
catch recaptcha missing exceptions

### PR DESCRIPTION
**Pull request by robguthrie**
@gdpelican how might I make an error show up on the form?

Either way, this is an improvement over current situation. Tested locally

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm, we should be doing this differently; we already have a validation on the user called `ensure_recaptcha`, so `require(:recaptcha)` should be unnecessary.

What happens if you take out all of this code, including the `require(:recaptcha)` line?

From there, we'll want to put a validation error like
```
%validation_errors{subject: "user", field: "recaptcha"}
```
which should show up just fine if the client recaptcha fails.

**Comment by gdpelican** [comment]
Oh, plus a check in `ensure_recaptcha` which just returns if RECAPTCHA_KEY isn't set.

**Comment by robguthrie** [comment]
Ok.. thanks for that guidance, have done that.

It's not displaying the validation message on failure, which I this is something about the auth_service and registration_model, I think if you have a look you'll probably understand why.

**Comment by gdpelican** [comment]
I'm hesitant about merging / deploying this at the moment because it currently prevents the creation of helper bot / Patrick Swayze in dev if you have RECAPTCHA_KEY set, which is not the thing we want. Should work fine in prod, but also potentially not (and the whole test suite runs without RECAPTCHA_KEY set, so we don't really know from that)

Not super confident on the right fix (I'm tempted to make a UserService#create and put the check there?), but would like to fix it before more.

**Comment by robguthrie** [comment]
no I don't think they overlap much, and we may keep the recaptcha as is
too, when trying to cut work down.

**Pull request closed without merging**
