### PR TITLE
[#1853] Use gravtar typo

### PR DESCRIPTION
**Pull request by marceloboeira**
Would this solve? Or there is some stuff on Transfirex ?

### CODE REVIEW

**Comment by gdpelican** [comment]
Hey @marceloboeira, thanks for the PR!

This is my preferred fix, but interested in hearing what @s01us has to say on the matter. Can we one-off script a key change for transifex somehow?

**Comment by marceloboeira** [comment]
@gdpelican branch is failing but I believe to be not related with my changes.

**Comment by denjello** [comment]
@marceloboeira You are right. I am having the same issue on another pull request.
```
(::) failed steps (::)
Circular dependency detected while autoloading constant NotificationsController (RuntimeError)
features/admin/unarchive_group.feature:12:in `Then they should be able to view their group page'
Failing Scenarios:
cucumber features/admin/unarchive_group.feature:8 # Scenario: Loomio admin unarchives group
```

**Comment by gdpelican** [comment]
It's an intermittent failure, I'll have a peek at why it's happening at
some point in the near future.

**Comment by denjello** [comment]
So what is the solution?

**Comment by s01us** [comment]
Changing one key everywhere requires some research.
I'll have a look if i have time tmrw.

**Comment by s01us** [comment]
Oh, to be honest, it's a typo in the key and this is used in one place in the app. I'm not keen to spend time editing this. 
There are more pressing translation questions, like offering users approriate translations reliabily on the front page. 

Basically we would have to upload this change to transifex for every file. Not hard, just takes time that i don't have

**Comment by marceloboeira** [comment]
@s01us I already searched for the translation, and replaced everywhere ...

**Comment by denjello** [comment]
@marceloboeira - Great, its in the pull-request, unfortunately the larger scope of the issue is getting those changes back into transifex - which seems to be a relatively labor-intensive task.

**Comment by gdpelican** [comment]
The other solution is to eat the typo and just put `t(:user_gravtar)` in the code, but it's a little tricky because we're switching on a variable in a partial.

If it was as simple as
**profile.html.haml**:
```
 = render 'avatar_setting_option', user: @user, kind: 'gravtar'
```

I might consider it, but any more work than that and it's just a hack that we'll have to spend more time on later.

**Comment by denjello** [comment]
As a professional translator I hate typos. As a coder I use terms to describe things. If that thing is already described and has a name, then when I want to use the word for the thing that exists I always spell it correctly, because otherwise I am not naming that thing. My opinion is fix the incoming descriptor:

`gravtar` > `gravatar`

Who knows where it might be needed later in further iterations of the code, and if every new coder has to read in the wiki "by the way, we misspelled gravatar". we're basically just propagating incompetence.

**Comment by gdpelican** [comment]
I appreciate your point @denjello, but this bug isn't high profile enough to warrant the Loomio team members spending any more than a trivial amount of time on it. 

I'm happy to look at a simple pull request to fix the problem if it can be done with a pull request, but I'm not happy ask @s01us to spend a bunch of time fixing something this minor. I'm also very happy to leave it as is until such time as we can get to a proper fix (or, until this page gets phased out of the interface)

**Comment by gdpelican** [comment]
Closing this for now, can reopen later if we find ourselves willing to spend some time on updating transifex to match this PR.

**Pull request closed without merging**
